### ISSUE TITLE
Mistake in puzzle text?

### ISSUE THREAD

**Issue by palver123** [atorch/probability_puzzles#3]
## Description

I cannot get my head around the reasoning in puzzle 17 (from 'Getting serious' section). The [description text](https://github.com/atorch/probability_puzzles/blob/master/app/src/main/res/values/strings.xml#L505) says:

> If instead you decided to accept any first proposal above 50, and - in case you reject the first - any second proposal whatsoever, your expected discounted payoff would be $60

How is it not 6325 / 101 ~ _$62.238_? The machine can propose from the interval [0, 100] so it can propose 101 different amounts.
 - I only accept the first proposal if it's above 50, meaning it is in [51, 100]. This interval has 50 elements and its average is (51+100)/2 = $75.5. The probability of accepting the first proposal is 50 / 101.
 - If I rejected the 1st proposal, I will accept anything from the interval [0, 100] (which has an average of $50). The probability of rejecting the 1st proposal is 51 / 100 and I will never reject the 2nd proposal.

Merging the two paths, I get EV = 50/101 * $75.5 + 51/101 * $50 = 6325 / 101.

Where did I make a mistake?

## By the way

Your app is great! I wish more people would be passionate about math and enjoyed it as much as I do.

**Comment by atorch** [comment]
Thank you for opening the app's first issue!  I'm glad you're enjoying the puzzles.

Here's a detailed explanation of the claim that

> If instead you decided to accept any first proposal above 50, and - in case you reject the first - any second proposal whatsoever, your expected discounted payoff would be $60

The key is that the distribution is uniform on the _interval_ [0, 100] (i.e. the distribution is continuous), as opposed to the finite set of integers {0, 1, 2, ..., 100}.  See https://en.wikipedia.org/wiki/Uniform_distribution_(continuous) versus https://en.wikipedia.org/wiki/Discrete_uniform_distribution.

The expected value of a draw above 50 is therefore (50+100)/2 = 75, and the expected value of _any_ draw is (0+100)/2 = 50.  The expected _discounted_ value of the policy "accept any first proposal over 50, and accept any second proposal whatsoever" is 0.5*75 + 0.5*0.9*50 = 60.  Note that the second term is multiplied both by 0.5 (which is the probability that you reject the first draw and wait until the second period), as well as the per-period discount factor of 0.9.

Does that make sense?

**Comment by palver123** [comment]
Ahh okay, it is continuous, that's it! I don't know why I assumed the amount to be an integer.

As for the 0.9 discount, I forgot to include it in the Github description, but originally I counted that too. It's just that it was years ago when I got stuck with this puzzle and recently took a look at it again.

Thanks for the quick answer, it is clear now.
